# Generated by Django 5.0.6 on 2025-09-30 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Campus Statistics',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_type', models.CharField(choices=[('General', 'General'), ('Admissions', 'Admissions'), ('Academic', 'Academic'), ('Placement', 'Placement'), ('Emergency', 'Emergency')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Events', 'Events'), ('Achievements', 'Achievements'), ('General', 'General'), ('Sports', 'Sports')], default='General', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='creativework',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='creativework',
            name='content_file',
        ),
        migrations.AddField(
            model_name='creativework',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='creative_works/files/'),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='author_department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Literature', 'Literature'), ('Technology', 'Technology'), ('Music', 'Music'), ('Photography', 'Photography'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='description',
            field=models.TextField(),
        ),
    ]
