# Generated by Django 5.0.6 on 2025-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.URLField(blank=True, help_text='Optional Google Drive or external link', null=True),
        ),
    ]
