# Generated by Django 5.0.6 on 2025-10-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notice_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section on homepage'),
        ),
    ]
