# Generated by Django 5.0.6 on 2025-10-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notice_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Events', 'Events'), ('Achievements', 'Achievements'), ('General', 'General'), ('Sports', 'Sports'), ('Achievement', 'Achievement'), ('News', 'News'), ('Announcement', 'Announcement'), ('Admission', 'Admission'), ('Event', 'Event'), ('Placement', 'Placement'), ('Research', 'Research'), ('Alumni', 'Alumni'), ('Cultural', 'Cultural')], default='General', max_length=50),
        ),
    ]
