# Generated by Django 5.0.6 on 2025-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news_author_news_expiry_date_news_external_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_link',
            field=models.URLField(blank=True, help_text='Google Drive link to PDF document', null=True),
        ),
    ]
