# Generated by Django 5.0.6 on 2025-10-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_officelocation_remove_contactinfo_contact_type_and_more'),
    ]

    operations = [
    ]
