# Generated by Django 5.0.6 on 2025-10-12 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251012_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('main_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('main_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('main_address', models.TextField(blank=True, null=True)),
                ('general_inquiries_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admissions_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('placement_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Quick Contact Information',
                'verbose_name_plural': 'Quick Contact Information',
            },
        ),
    ]
