# Generated by Django 5.0.6 on 2025-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quickcontactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs'),
        ),
        migrations.AddField(
            model_name='department',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AddField(
            model_name='department',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Alternative to hero_image file', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='programs_offered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='department',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
