# Generated by Django 5.0.6 on 2025-10-13 07:23

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_department_achievements_department_facilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='department',
            name='hero_image_url',
        ),
        migrations.AlterField(
            model_name='department',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.department_hero_upload_path),
        ),
        migrations.CreateModel(
            name='DepartmentGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=core.models.department_gallery_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.department')),
            ],
            options={
                'ordering': ['department', 'display_order', 'created_at'],
            },
        ),
    ]
