# Generated by Django 5.0.6 on 2025-10-13 07:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_department_gallery_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentgalleryimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='departmentgalleryimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.department_gallery_upload_path),
        ),
        migrations.AlterField(
            model_name='departmentgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.department_gallery_upload_path),
        ),
    ]
