# Generated by Django 5.0.6 on 2025-10-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_departmentgalleryimage_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='file_url',
            field=models.URLField(blank=True, help_text='External URL for magazine file (Google Drive, Dropbox, etc.)', max_length=500, null=True),
        ),
    ]
