# Generated by Django 5.2.7 on 2025-10-19 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_magazine_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timetable_type', models.CharField(choices=[('class', 'Class Timetable'), ('exam', 'Exam Schedule'), ('event', 'Event Schedule'), ('lab', 'Lab Schedule')], default='class', max_length=20)),
                ('semester', models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=10, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('timetable_file', models.FileField(blank=True, null=True, upload_to='timetables/')),
                ('timetable_image', models.ImageField(blank=True, null=True, upload_to='timetables/images/')),
                ('external_link', models.URLField(blank=True, help_text='Google Drive or external link to timetable', null=True)),
                ('schedule_data', models.JSONField(blank=True, default=dict, help_text='JSON data for schedule if needed')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.department')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
