# Generated by Django 5.2.7 on 2025-10-22 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timetable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='content_url',
            field=models.URLField(blank=True, help_text='External content file URL', null=True),
        ),
        migrations.AddField(
            model_name='creativework',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', null=True),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='author_department',
            field=models.CharField(blank=True, choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='category',
            field=models.CharField(choices=[('Art & Design', 'Art & Design'), ('Photography', 'Photography'), ('Poetry & Literature', 'Poetry & Literature'), ('Music & Dance', 'Music & Dance'), ('Digital Media', 'Digital Media'), ('Innovation & Projects', 'Innovation & Projects'), ('Digital Art', 'Digital Art'), ('Music Composition', 'Music Composition'), ('Writing', 'Writing'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='creativework',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Art & Design', 'Art & Design'), ('Photography', 'Photography'), ('Poetry & Literature', 'Poetry & Literature'), ('Music & Dance', 'Music & Dance'), ('Digital Media', 'Digital Media'), ('Innovation & Projects', 'Innovation & Projects'), ('Digital Art', 'Digital Art'), ('Music Composition', 'Music Composition'), ('Writing', 'Writing'), ('Other', 'Other')], max_length=50)),
                ('department', models.CharField(blank=True, choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('Other', 'Other')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_submissions/')),
                ('file', models.FileField(blank=True, null=True, upload_to='student_submissions/files/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL', null=True)),
                ('file_url', models.URLField(blank=True, help_text='External file URL', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
