# Generated by Django 5.2.7 on 2025-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_creativework_content_url_creativework_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram post/reel URL', null=True),
        ),
        migrations.AddField(
            model_name='creativework',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram post/reel URL', null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
