# Generated by Django 5.2.7 on 2025-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_creativework_instagram_url_creativework_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='category',
            field=models.CharField(choices=[('Art & Design', 'Art & Design'), ('Photography', 'Photography'), ('Poetry & Literature', 'Poetry & Literature'), ('Music & Dance', 'Music & Dance'), ('Digital Media', 'Digital Media'), ('Innovation & Projects', 'Innovation & Projects'), ('Digital Art', 'Digital Art'), ('Music Composition', 'Music Composition'), ('Writing', 'Writing'), ('Design', 'Design'), ('Video', 'Video'), ('Innovation', 'Innovation'), ('Technology', 'Technology'), ('Research', 'Research'), ('Startup', 'Startup'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='category',
            field=models.CharField(choices=[('Art & Design', 'Art & Design'), ('Photography', 'Photography'), ('Poetry & Literature', 'Poetry & Literature'), ('Music & Dance', 'Music & Dance'), ('Digital Media', 'Digital Media'), ('Innovation & Projects', 'Innovation & Projects'), ('Digital Art', 'Digital Art'), ('Music Composition', 'Music Composition'), ('Writing', 'Writing'), ('Design', 'Design'), ('Video', 'Video'), ('Innovation', 'Innovation'), ('Technology', 'Technology'), ('Research', 'Research'), ('Startup', 'Startup'), ('Other', 'Other')], max_length=50),
        ),
    ]
