# Generated by Django 5.2.7 on 2025-10-25 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_creativework_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website_link',
            field=models.URLField(blank=True, help_text='Club website or social media link', null=True),
        ),
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('competition', 'Competition'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('technical', 'Technical Event'), ('club_activity', 'Club Activity'), ('notice', 'Notice/Announcement')], default='festival', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer', models.CharField(blank=True, help_text='Organizing club or department', max_length=200, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('club', models.ForeignKey(blank=True, help_text='Associated club (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.club')),
            ],
            options={
                'verbose_name': 'Campus Event',
                'verbose_name_plural': 'Campus Events',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
